//! Provider catalog: a compile-time baseline plus a live discovery overlay.
//!
//! The baseline is a JSON document embedded at build time via `include_str!`, so
//! a provider's base URL, wire format and auth class cost zero runtime I/O. It
//! is parsed once, lazily, into a [`Registry`]. That is the *preferred* path and
//! stays the only one on the request path.
//!
//! [`discovery`] is the P1 overlay for when a provider is not in the baseline:
//! it fetches models.dev, caches it stale-while-revalidate, and never empties a
//! running proxy's model list on a network failure. [`vector`] is the
//! feature-gated model-id lookup, off by default because it costs RAM.
//!
//! This crate deliberately does **not** define any provider wire format. What a
//! `wire_format` label means on the wire is `ar-translate`'s to implement; here
//! it is only a lookup key. AGENTS.md is explicit: never invent provider wire
//! formats.

#![deny(missing_docs)]

pub mod discovery;
pub mod vector;

use std::collections::BTreeMap;
use std::sync::OnceLock;

use ar_core::Strng;
use serde::{Deserialize, Serialize};

/// The embedded catalog. Generated by `ar import --from omniroute --path
/// <OmniRoute/open-sse/config/providers>`; edit the importer, not this file.
///
/// Compact JSON on purpose: the catalog is compiled into every binary via
/// `include_str!`, so whitespace is dead weight in the binary rather than in a
/// repo file. Pretty-print it on demand with `ar import` + `python3 -m json.tool`.
const CATALOG_JSON: &str = include_str!("registry.json");

/// How a provider proves who it is.
///
/// P0 is API-key only. OAuth / browser-session providers (`claude-web`,
/// `gemini-web`, `codex-web`) are an explicit non-goal for P0 (docs/00), and
/// adding the variants ahead of the crates that need them would make the enum
/// claim support that does not exist.
///
/// The upstream label for a provider that needs something else lives in
/// [`ProviderDef::auth_kind`], verbatim, so `ar doctor` can name what it would
/// take without this enum claiming P0 can do it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AuthClass {
    /// A single bearer-style secret supplied by the user.
    ApiKey,
}

/// The wire dialect a provider speaks, as a lookup label only.
///
/// Carries every dialect the catalog records, including the ones `ar-exec`
/// refuses. Refusing is a runtime verdict (`ExecError::UnsupportedWire`), not a
/// reason to leave the label out of the catalog: a provider that is not
/// routable today is still the provider a user will find in OmniRoute, and
/// `ar doctor` naming it is more useful than `ar doctor` not knowing it exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum WireFormat {
    /// OpenAI chat-completions shape.
    Openai,
    /// Anthropic messages shape.
    Anthropic,
    /// OpenAI Responses-API shape.
    OpenaiResponses,
    /// Google Generative Language shape.
    Gemini,
    /// Antigravity's dialect.
    Antigravity,
    /// Cursor's dialect.
    Cursor,
    /// CLOVA Studio's dialect.
    Clova,
    /// A provider-specific dialect with no shared label.
    Custom,
    /// Kiro's dialect.
    Kiro,
}

impl WireFormat {
    /// The spelling used in `registry.json` and in TOON output.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Openai => "openai",
            Self::Anthropic => "anthropic",
            Self::OpenaiResponses => "openai-responses",
            Self::Gemini => "gemini",
            Self::Antigravity => "antigravity",
            Self::Cursor => "cursor",
            Self::Clova => "clova",
            Self::Custom => "custom",
            Self::Kiro => "kiro",
        }
    }
}

/// Parses an upstream `RegistryEntry.format` value.
///
/// Unknown labels become [`WireFormat::Custom`]: the dialect exists and is not
/// one of the eight named shapes, and `ar-exec` refuses both the same way.
#[must_use]
pub fn wire_format(name: &str) -> WireFormat {
    match name {
        "openai" => WireFormat::Openai,
        // OmniRoute spells the messages dialect `claude`.
        "claude" | "anthropic" => WireFormat::Anthropic,
        "openai-responses" => WireFormat::OpenaiResponses,
        "gemini" => WireFormat::Gemini,
        "antigravity" => WireFormat::Antigravity,
        "cursor" => WireFormat::Cursor,
        "clova" => WireFormat::Clova,
        "kiro" => WireFormat::Kiro,
        _ => WireFormat::Custom,
    }
}

/// One model's price, in USD per million tokens.
///
/// Dollars rather than the micro-dollars `ar-tokens` computes with: the catalog
/// is generated from an upstream table quoted in dollars, and a value that
/// round-trips through `f64` here and converts once at load keeps the generated
/// JSON readable instead of storing every rate pre-scaled.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Price {
    /// USD per million prompt tokens.
    pub input_usd_per_mtok: f64,
    /// USD per million completion tokens.
    pub output_usd_per_mtok: f64,
}

/// Everything Artificial Route knows about one provider at compile time.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProviderDef {
    /// Upstream API root, without a trailing slash.
    pub base_url: String,
    /// Dialect label; the translation itself lives in `ar-translate`.
    pub wire_format: WireFormat,
    /// Credential kind required to call this provider.
    pub auth: AuthClass,
    /// Conventional environment variable name, for `doctor` hints and docs.
    ///
    /// Advisory only: nothing reads it at runtime, so a user may keep the secret
    /// in any file `ar-config` can read.
    pub env_hint: String,
    /// Provider-native model ids this build can route to, as the upstream
    /// registry spells them.
    pub models: Vec<Strng>,
    /// Prices for the models that have them, keyed by the same spelling as
    /// [`ProviderDef::models`].
    ///
    /// Absent for a model means the upstream pricing table had no row for it,
    /// which is a different fact from "priced at zero" and has to stay
    /// distinguishable: `cost-optimized` sorts an unpriced target last, and a
    /// hard budget must not read a missing row as free.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub prices: BTreeMap<Strng, Price>,
    /// OmniRoute's executor id, verbatim.
    ///
    /// The transport that serves this provider, which is usually not its wire
    /// format: `claude` format over the `bedrock` executor is a real pair.
    /// Recorded so `ar doctor` can say which executor a provider needs.
    #[serde(default)]
    pub executor: Strng,
    /// OmniRoute's `authType`, verbatim (`apikey`, `oauth`, `optional`, `none`).
    ///
    /// Wider than [`ProviderDef::auth`], which stays the P0-arbitable class. A
    /// provider labelled `oauth` is in the catalog and named by `doctor`, but
    /// `AuthClass` still says `ApiKey` because that is the only thing this build
    /// can send.
    #[serde(default)]
    pub auth_kind: Strng,
    /// Whether this provider is billed at a flat rate rather than per token.
    ///
    /// A subscription or coding plan. It still needs per-token rows for
    /// pre-flight estimates; only the charge collapses to zero.
    #[serde(default, skip_serializing_if = "is_false")]
    pub flat_rate: bool,
}

/// `skip_serializing_if` helper: keeps `flat_rate: false` out of the JSON.
fn is_false(v: &bool) -> bool {
    !*v
}

/// Provider definitions keyed by provider id, in sorted-id order.
///
/// Sorted rather than hashed so a regenerated `registry.json` is byte-stable:
/// two imports of the same upstream tree produce the same file, which is what
/// makes it reviewable in a diff.
#[derive(Debug, Default)]
pub struct Registry {
    defs: BTreeMap<Strng, ProviderDef>,
}

impl Registry {
    /// Looks up a provider by id, borrowing the caller's id so a lookup on a
    /// request path does not allocate.
    pub fn get(&self, id: &str) -> Option<&ProviderDef> {
        self.defs.get(id)
    }

    /// Number of providers in the catalog.
    pub fn len(&self) -> usize {
        self.defs.len()
    }

    /// Whether the catalog is empty. Never true for a valid build.
    pub fn is_empty(&self) -> bool {
        self.defs.is_empty()
    }

    /// Iterates `(id, def)` pairs in id order.
    pub fn iter(&self) -> impl Iterator<Item = (&Strng, &ProviderDef)> {
        self.defs.iter()
    }

    /// The price of one provider/model pair, if the catalog has a row for it.
    ///
    /// Both halves are matched exactly, as the catalog stores them: the ids come
    /// from the same generated table, so a lookup that misses means the row
    /// genuinely is absent rather than that the caller spelled it differently.
    pub fn price(&self, provider: &str, model: &str) -> Option<Price> {
        self.defs.get(provider).and_then(|d| d.prices.get(model)).copied()
    }

    /// Every `(provider, model, price)` row in the catalog.
    ///
    /// The loader input for `ar-tokens::PricingTable`, so the two halves cannot
    /// disagree about which rows exist.
    pub fn prices(&self) -> impl Iterator<Item = (&str, &str, Price)> {
        self.defs.iter().flat_map(|(provider, def)| {
            def.prices.iter().map(move |(model, price)| (provider.as_ref(), model.as_ref(), *price))
        })
    }

    /// Every provider id billed at a flat rate.
    pub fn flat_rate_providers(&self) -> impl Iterator<Item = &str> {
        self.defs.iter().filter(|(_, d)| d.flat_rate).map(|(id, _)| id.as_ref())
    }
}

/// Returns the process-wide catalog, parsing it on first call.
///
/// Lazy on purpose: `ar --version` must exit before this runs (docs/06
/// `--version` fast path), so the JSON parse is not on that path at all.
///
/// # Panics
///
/// Panics if the compiled-in catalog is malformed. That is a build-time defect
/// (`registry.json` is a source file, not user input), so a panic at first use
/// is the honest signal; it cannot be triggered by a request.
pub fn global() -> &'static Registry {
    static REGISTRY: OnceLock<Registry> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        let defs: BTreeMap<Strng, ProviderDef> =
            serde_json::from_str(CATALOG_JSON).expect("embedded registry.json is malformed");
        // A generated base URL that is a bare SCREAMING_CASE identifier means the
        // reader lost a `const` chain. Panic here rather than route to that
        // literal string: an entry that cannot be reached is a build-time defect,
        // and the importer already reports those by name on stderr. An empty base
        // URL is allowed (a provider whose endpoint resolves at request time) and
        // a non-http one is allowed (a CLI or websocket transport).
        assert!(
            defs.values().all(|d| !looks_unresolved(&d.base_url)),
            "registry.json holds an unresolved base URL; regenerate it with `ar import --from omniroute`"
        );
        Registry { defs }
    })
}

/// Whether a base URL is a `const` name the reader failed to substitute.
fn looks_unresolved(url: &str) -> bool {
    !url.is_empty()
        && !url.contains("://")
        && url.chars().all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn looks_up_openai_when_id_known() {
        assert_eq!(global().get("openai").map(|d| d.auth), Some(AuthClass::ApiKey));
    }

    #[test]
    fn ships_the_full_omniroute_catalog() {
        // A regenerated catalog that lost an order of magnitude is a broken
        // importer, not a smaller world: the parity manifest is 276 providers /
        // 1061 models, and the floor here is well below that so a partial
        // scrape still fails.
        assert!(
            global().len() >= 250,
            "catalog holds {} providers, expected the full OmniRoute set",
            global().len()
        );
        let models: usize = global().iter().map(|(_, d)| d.models.len()).sum();
        assert!(models >= 900, "catalog holds {models} models, expected >= 900");
    }

    #[test]
    fn carries_prices_for_the_models_that_have_them() {
        let price = global().price("openai", "gpt-5.4").expect("openai/gpt-5.4 is priced upstream");
        assert!(price.input_usd_per_mtok > 0.0 && price.output_usd_per_mtok > 0.0, "{price:?}");
        assert!(global().price("openai", "no-such-model").is_none());
    }

    #[test]
    fn prices_openai_cheaper_on_a_small_model_than_a_large_one() {
        // The assertion the cost-optimized test depends on: a real price
        // difference, so a cheapest-pick proves it read the table rather than
        // the input order.
        let mini = global().price("openai", "gpt-5.4-nano").expect("priced").input_usd_per_mtok;
        let full = global().price("openai", "gpt-5.4").expect("priced").input_usd_per_mtok;
        assert!(mini < full, "nano {mini} should be under full {full}");
    }

    #[test]
    fn keeps_flat_rate_providers_marked() {
        let flat: Vec<&str> = global().flat_rate_providers().collect();
        assert!(flat.contains(&"claude"), "the Claude Code plan is flat-rate: {flat:?}");
        // An explicitly excluded metered provider: `byteplus` is per-token.
        assert!(!flat.contains(&"byteplus"), "{flat:?}");
    }
}
